// data/productsData.js

module.exports = [
  {
    name: "Emerald Ring",
    description: "Elegant emerald ring set in gold.",
    image: "https://kirikiri.in/cdn/shop/products/20220920_120134.jpg?v=1743541381&width=1000",
    price: 129.99,
    quantity: 10,
    material: "Gold",
    size: "6",
    gemstone: "Emerald",
    cut: "Oval",
    categoryName: "Rings",
  },
  {
    name: "Diamond Necklace",
    description: "Sparkling diamond necklace for special occasions.",
    image: "https://kirikiri.in/cdn/shop/products/13copy1.jpg?v=1648646555&width=1000",
    price: 499.99,
    quantity: 5,
    material: "Platinum",
    size: "M",
    gemstone: "Diamond",
    cut: "Round",
    categoryName: "Necklaces",
  },
  {
    name: "Silver Bracelet",
    description: "Simple yet elegant silver bracelet.",
    image: "https://kirikiri.in/cdn/shop/products/2_7cb7311c-6092-4cae-ab11-8ebfb17f76ce.jpg?v=1664434536&width=1000",
    price: 79.99,
    quantity: 15,
    material: "Silver",
    size: "Adjustable",
    gemstone: "",
    cut: "",
    categoryName: "Bracelets",
  },
  {
    name: "Emerald Ring",
    description: "Elegant emerald ring set in gold.",
    image: "https://kirikiri.in/cdn/shop/products/20220920_120134.jpg?v=1743541381&width=1000",
    price: 129.99,
    quantity: 10,
    material: "Gold",
    size: "6",
    gemstone: "Emerald",
    cut: "Oval",
    categoryName: "Rings",
  },
  {
    name: "Diamond Necklace",
    description: "Sparkling diamond necklace for special occasions.",
    image: "https://kirikiri.in/cdn/shop/products/13copy1.jpg?v=1648646555&width=1000",
    price: 499.99,
    quantity: 5,
    material: "Platinum",
    size: "M",
    gemstone: "Diamond",
    cut: "Round",
    categoryName: "Necklaces",
  },
  {
    name: "Silver Bracelet",
    description: "Simple yet elegant silver bracelet.",
    image: "https://kirikiri.in/cdn/shop/products/2_7cb7311c-6092-4cae-ab11-8ebfb17f76ce.jpg?v=1664434536&width=1000",
    price: 79.99,
    quantity: 15,
    material: "Silver",
    size: "Adjustable",
    gemstone: "",
    cut: "",
    categoryName: "Bracelets",
  },
  {
    name: "Emerald Ring",
    description: "Elegant emerald ring set in gold.",
    image: "https://kirikiri.in/cdn/shop/products/20220920_120134.jpg?v=1743541381&width=1000",
    price: 129.99,
    quantity: 10,
    material: "Gold",
    size: "6",
    gemstone: "Emerald",
    cut: "Oval",
    categoryName: "Rings",
  },
  {
    name: "Diamond Necklace",
    description: "Sparkling diamond necklace for special occasions.",
    image: "https://kirikiri.in/cdn/shop/products/13copy1.jpg?v=1648646555&width=1000",
    price: 499.99,
    quantity: 5,
    material: "Platinum",
    size: "M",
    gemstone: "Diamond",
    cut: "Round",
    categoryName: "Necklaces",
  },
  {
    name: "Silver Bracelet",
    description: "Simple yet elegant silver bracelet.",
    image: "https://kirikiri.in/cdn/shop/products/2_7cb7311c-6092-4cae-ab11-8ebfb17f76ce.jpg?v=1664434536&width=1000",
    price: 79.99,
    quantity: 15,
    material: "Silver",
    size: "Adjustable",
    gemstone: "",
    cut: "",
    categoryName: "Bracelets",
  },
  {
    name: "Emerald Ring",
    description: "Elegant emerald ring set in gold.",
    image: "https://kirikiri.in/cdn/shop/products/20220920_120134.jpg?v=1743541381&width=1000",
    price: 129.99,
    quantity: 10,
    material: "Gold",
    size: "6",
    gemstone: "Emerald",
    cut: "Oval",
    categoryName: "Rings",
  },
  {
    name: "Diamond Necklace",
    description: "Sparkling diamond necklace for special occasions.",
    image: "https://kirikiri.in/cdn/shop/products/13copy1.jpg?v=1648646555&width=1000",
    price: 499.99,
    quantity: 5,
    material: "Platinum",
    size: "M",
    gemstone: "Diamond",
    cut: "Round",
    categoryName: "Necklaces",
  },
  {
    name: "Silver Bracelet",
    description: "Simple yet elegant silver bracelet.",
    image: "https://kirikiri.in/cdn/shop/products/2_7cb7311c-6092-4cae-ab11-8ebfb17f76ce.jpg?v=1664434536&width=1000",
    price: 79.99,
    quantity: 15,
    material: "Silver",
    size: "Adjustable",
    gemstone: "",
    cut: "",
    categoryName: "Bracelets",
  },
  {
    name: "Emerald Ring",
    description: "Elegant emerald ring set in gold.",
    image: "https://kirikiri.in/cdn/shop/products/20220920_120134.jpg?v=1743541381&width=1000",
    price: 129.99,
    quantity: 10,
    material: "Gold",
    size: "6",
    gemstone: "Emerald",
    cut: "Oval",
    categoryName: "Rings",
  },
  {
    name: "Diamond Necklace",
    description: "Sparkling diamond necklace for special occasions.",
    image: "https://kirikiri.in/cdn/shop/products/13copy1.jpg?v=1648646555&width=1000",
    price: 499.99,
    quantity: 5,
    material: "Platinum",
    size: "M",
    gemstone: "Diamond",
    cut: "Round",
    categoryName: "Necklaces",
  },
  {
    name: "Silver Bracelet",
    description: "Simple yet elegant silver bracelet.",
    image: "https://kirikiri.in/cdn/shop/products/2_7cb7311c-6092-4cae-ab11-8ebfb17f76ce.jpg?v=1664434536&width=1000",
    price: 79.99,
    quantity: 15,
    material: "Silver",
    size: "Adjustable",
    gemstone: "",
    cut: "",
    categoryName: "Bracelets",
  },
  {
    name: "Emerald Ring",
    description: "Elegant emerald ring set in gold.",
    image: "https://kirikiri.in/cdn/shop/products/20220920_120134.jpg?v=1743541381&width=1000",
    price: 129.99,
    quantity: 10,
    material: "Gold",
    size: "6",
    gemstone: "Emerald",
    cut: "Oval",
    categoryName: "Rings",
  },
  {
    name: "Diamond Necklace",
    description: "Sparkling diamond necklace for special occasions.",
    image: "https://kirikiri.in/cdn/shop/products/13copy1.jpg?v=1648646555&width=1000",
    price: 499.99,
    quantity: 5,
    material: "Platinum",
    size: "M",
    gemstone: "Diamond",
    cut: "Round",
    categoryName: "Necklaces",
  },
  {
    name: "Silver Bracelet",
    description: "Simple yet elegant silver bracelet.",
    image: "https://kirikiri.in/cdn/shop/products/2_7cb7311c-6092-4cae-ab11-8ebfb17f76ce.jpg?v=1664434536&width=1000",
    price: 79.99,
    quantity: 15,
    material: "Silver",
    size: "Adjustable",
    gemstone: "",
    cut: "",
    categoryName: "Bracelets",
  },
  {
    name: "Emerald Ring",
    description: "Elegant emerald ring set in gold.",
    image: "https://kirikiri.in/cdn/shop/products/20220920_120134.jpg?v=1743541381&width=1000",
    price: 129.99,
    quantity: 10,
    material: "Gold",
    size: "6",
    gemstone: "Emerald",
    cut: "Oval",
    categoryName: "Rings",
  },
  {
    name: "Diamond Necklace",
    description: "Sparkling diamond necklace for special occasions.",
    image: "https://kirikiri.in/cdn/shop/products/13copy1.jpg?v=1648646555&width=1000",
    price: 499.99,
    quantity: 5,
    material: "Platinum",
    size: "M",
    gemstone: "Diamond",
    cut: "Round",
    categoryName: "Necklaces",
  },
  {
    name: "Silver Bracelet",
    description: "Simple yet elegant silver bracelet.",
    image: "https://kirikiri.in/cdn/shop/products/2_7cb7311c-6092-4cae-ab11-8ebfb17f76ce.jpg?v=1664434536&width=1000",
    price: 79.99,
    quantity: 15,
    material: "Silver",
    size: "Adjustable",
    gemstone: "",
    cut: "",
    categoryName: "Bracelets",
  },
  {
    name: "Emerald Ring",
    description: "Elegant emerald ring set in gold.",
    image: "https://kirikiri.in/cdn/shop/products/20220920_120134.jpg?v=1743541381&width=1000",
    price: 129.99,
    quantity: 10,
    material: "Gold",
    size: "6",
    gemstone: "Emerald",
    cut: "Oval",
    categoryName: "Rings",
  },
  {
    name: "Diamond Necklace",
    description: "Sparkling diamond necklace for special occasions.",
    image: "https://kirikiri.in/cdn/shop/products/13copy1.jpg?v=1648646555&width=1000",
    price: 499.99,
    quantity: 5,
    material: "Platinum",
    size: "M",
    gemstone: "Diamond",
    cut: "Round",
    categoryName: "Necklaces",
  },
  {
    name: "Silver Bracelet",
    description: "Simple yet elegant silver bracelet.",
    image: "https://kirikiri.in/cdn/shop/products/2_7cb7311c-6092-4cae-ab11-8ebfb17f76ce.jpg?v=1664434536&width=1000",
    price: 79.99,
    quantity: 15,
    material: "Silver",
    size: "Adjustable",
    gemstone: "",
    cut: "",
    categoryName: "Bracelets",
  },
  {
    name: "Emerald Ring",
    description: "Elegant emerald ring set in gold.",
    image: "https://kirikiri.in/cdn/shop/products/20220920_120134.jpg?v=1743541381&width=1000",
    price: 129.99,
    quantity: 10,
    material: "Gold",
    size: "6",
    gemstone: "Emerald",
    cut: "Oval",
    categoryName: "Rings",
  },
  {
    name: "Diamond Necklace",
    description: "Sparkling diamond necklace for special occasions.",
    image: "https://kirikiri.in/cdn/shop/products/13copy1.jpg?v=1648646555&width=1000",
    price: 499.99,
    quantity: 5,
    material: "Platinum",
    size: "M",
    gemstone: "Diamond",
    cut: "Round",
    categoryName: "Necklaces",
  },
  {
    name: "Silver Bracelet",
    description: "Simple yet elegant silver bracelet.",
    image: "https://kirikiri.in/cdn/shop/products/2_7cb7311c-6092-4cae-ab11-8ebfb17f76ce.jpg?v=1664434536&width=1000",
    price: 79.99,
    quantity: 15,
    material: "Silver",
    size: "Adjustable",
    gemstone: "",
    cut: "",
    categoryName: "Bracelets",
  },
  {
    name: "Emerald Ring",
    description: "Elegant emerald ring set in gold.",
    image: "https://kirikiri.in/cdn/shop/products/20220920_120134.jpg?v=1743541381&width=1000",
    price: 129.99,
    quantity: 10,
    material: "Gold",
    size: "6",
    gemstone: "Emerald",
    cut: "Oval",
    categoryName: "Rings",
  },
  {
    name: "Diamond Necklace",
    description: "Sparkling diamond necklace for special occasions.",
    image: "https://kirikiri.in/cdn/shop/products/13copy1.jpg?v=1648646555&width=1000",
    price: 499.99,
    quantity: 5,
    material: "Platinum",
    size: "M",
    gemstone: "Diamond",
    cut: "Round",
    categoryName: "Necklaces",
  },
  {
    name: "Silver Bracelet",
    description: "Simple yet elegant silver bracelet.",
    image: "https://kirikiri.in/cdn/shop/products/2_7cb7311c-6092-4cae-ab11-8ebfb17f76ce.jpg?v=1664434536&width=1000",
    price: 79.99,
    quantity: 15,
    material: "Silver",
    size: "Adjustable",
    gemstone: "",
    cut: "",
    categoryName: "Bracelets",
  },
  {
    name: "Emerald Ring",
    description: "Elegant emerald ring set in gold.",
    image: "https://kirikiri.in/cdn/shop/products/20220920_120134.jpg?v=1743541381&width=1000",
    price: 129.99,
    quantity: 10,
    material: "Gold",
    size: "6",
    gemstone: "Emerald",
    cut: "Oval",
    categoryName: "Rings",
  },
  {
    name: "Diamond Necklace",
    description: "Sparkling diamond necklace for special occasions.",
    image: "https://kirikiri.in/cdn/shop/products/13copy1.jpg?v=1648646555&width=1000",
    price: 499.99,
    quantity: 5,
    material: "Platinum",
    size: "M",
    gemstone: "Diamond",
    cut: "Round",
    categoryName: "Necklaces",
  },
  {
    name: "Silver Bracelet",
    description: "Simple yet elegant silver bracelet.",
    image: "https://kirikiri.in/cdn/shop/products/2_7cb7311c-6092-4cae-ab11-8ebfb17f76ce.jpg?v=1664434536&width=1000",
    price: 79.99,
    quantity: 15,
    material: "Silver",
    size: "Adjustable",
    gemstone: "",
    cut: "",
    categoryName: "Bracelets",
  },
  {
    name: "Emerald Ring",
    description: "Elegant emerald ring set in gold.",
    image: "https://kirikiri.in/cdn/shop/products/20220920_120134.jpg?v=1743541381&width=1000",
    price: 129.99,
    quantity: 10,
    material: "Gold",
    size: "6",
    gemstone: "Emerald",
    cut: "Oval",
    categoryName: "Rings",
  },
  {
    name: "Diamond Necklace",
    description: "Sparkling diamond necklace for special occasions.",
    image: "https://kirikiri.in/cdn/shop/products/13copy1.jpg?v=1648646555&width=1000",
    price: 499.99,
    quantity: 5,
    material: "Platinum",
    size: "M",
    gemstone: "Diamond",
    cut: "Round",
    categoryName: "Necklaces",
  },
  {
    name: "Silver Bracelet",
    description: "Simple yet elegant silver bracelet.",
    image: "https://kirikiri.in/cdn/shop/products/2_7cb7311c-6092-4cae-ab11-8ebfb17f76ce.jpg?v=1664434536&width=1000",
    price: 79.99,
    quantity: 15,
    material: "Silver",
    size: "Adjustable",
    gemstone: "",
    cut: "",
    categoryName: "Bracelets",
  },
  {
    name: "Emerald Ring",
    description: "Elegant emerald ring set in gold.",
    image: "https://kirikiri.in/cdn/shop/products/20220920_120134.jpg?v=1743541381&width=1000",
    price: 129.99,
    quantity: 10,
    material: "Gold",
    size: "6",
    gemstone: "Emerald",
    cut: "Oval",
    categoryName: "Rings",
  },
  {
    name: "Diamond Necklace",
    description: "Sparkling diamond necklace for special occasions.",
    image: "https://kirikiri.in/cdn/shop/products/13copy1.jpg?v=1648646555&width=1000",
    price: 499.99,
    quantity: 5,
    material: "Platinum",
    size: "M",
    gemstone: "Diamond",
    cut: "Round",
    categoryName: "Necklaces",
  },
  {
    name: "Silver Bracelet",
    description: "Simple yet elegant silver bracelet.",
    image: "https://kirikiri.in/cdn/shop/products/2_7cb7311c-6092-4cae-ab11-8ebfb17f76ce.jpg?v=1664434536&width=1000",
    price: 79.99,
    quantity: 15,
    material: "Silver",
    size: "Adjustable",
    gemstone: "",
    cut: "",
    categoryName: "Bracelets",
  },
  {
    name: "Emerald Ring",
    description: "Elegant emerald ring set in gold.",
    image: "https://kirikiri.in/cdn/shop/products/20220920_120134.jpg?v=1743541381&width=1000",
    price: 129.99,
    quantity: 10,
    material: "Gold",
    size: "6",
    gemstone: "Emerald",
    cut: "Oval",
    categoryName: "Rings",
  },
  {
    name: "Diamond Necklace",
    description: "Sparkling diamond necklace for special occasions.",
    image: "https://kirikiri.in/cdn/shop/products/13copy1.jpg?v=1648646555&width=1000",
    price: 499.99,
    quantity: 5,
    material: "Platinum",
    size: "M",
    gemstone: "Diamond",
    cut: "Round",
    categoryName: "Necklaces",
  },
  {
    name: "Silver Bracelet",
    description: "Simple yet elegant silver bracelet.",
    image: "https://kirikiri.in/cdn/shop/products/2_7cb7311c-6092-4cae-ab11-8ebfb17f76ce.jpg?v=1664434536&width=1000",
    price: 79.99,
    quantity: 15,
    material: "Silver",
    size: "Adjustable",
    gemstone: "",
    cut: "",
    categoryName: "Bracelets",
  }
];
